# Generated by Django 4.2.7 on 2023-11-19 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(null=True, upload_to='')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('preco_minimo', models.FloatField(null=True)),
                ('combustivel', models.CharField(max_length=50)),
                ('ano', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=11)),
                ('conta_bancaria', models.CharField(max_length=40)),
                ('data_demissao', models.DateTimeField(blank=True, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregue', models.BooleanField(default=False)),
                ('endereco', models.CharField(max_length=100)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.carro')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.vendedores')),
            ],
        ),
    ]
