# Generated by Django 4.2.7 on 2023-11-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedores',
            name='conta_bancaria',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='endereco',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
