# Generated by Django 4.2.7 on 2023-11-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_vendedores_conta_bancaria_alter_vendedores_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='preco',
            field=models.FloatField(null=True),
        ),
    ]
