# Generated by Django 4.2.7 on 2023-11-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_venda_data_venda_venda_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='disponivel',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
