# Generated by Django 4.2.7 on 2023-11-20 16:49

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_carro_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='foto',
            field=models.FileField(null=True, upload_to=project.models.Carro.upload_to_directory),
        ),
    ]
